#!/bin/bash
REMMINA_EXTERNAL_TOOLS_DIR=/usr/share/remmina/external_tools
REMMINA_EXTERNAL_TOOLS_DEFAULTS=(
    remmina_filezilla_sftp_pki.sh
    remmina_filezilla_sftp.sh
    remmina_nslookup.sh
    remmina_ping.sh 
    remmina_traceroute.sh
    )